config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#show"

  resources :weights,          only: [:index]
  resources :perimeters,       only: [:index]
  resources :daily_activities, only: [:index]
  resources :hungers,          only: [:index, :destroy, :new, :create]
  resources :priorities,       only: [:index, :destroy, :new, :create]

  resources :days, only: [:new, :create] do
    member do
      scope module: :days do
        resource :daily_activity, only: [:new, :create]
        resource :weight,         only: [:new, :create]
        resource :perimeter,      only: [:new, :create]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_activity.rb
class DailyActivity < ApplicationRecord
  belongs_to :day

  delegate :registered_on, to: :day
end

app/models/day.rb
class Day < ApplicationRecord
  validates :registered_on, presence: true, uniqueness: { scope: :user_id }
  validate :registered_on_past_or_present_only

  belongs_to :user

  with_options dependent: :destroy do
    has_one :daily_activity
    has_one :perimeter
    has_one :weight
  end

  enum status: %i{ pending restarted completed }

  def registered_on_past_or_present_only
    return unless registered_on.present? && registered_on > Date.today
    errors.add(:registered_on, :past_or_present_only)
  end
end

app/models/hunger.rb
class Hunger < ApplicationRecord
  validates :local, :question, :registered_at, :sensation,
            presence: true

  belongs_to :user

  enum classification: %i{ hunger desire crave }
end

app/models/perimeter.rb
class Perimeter < ApplicationRecord
  validates :abdomen, :arm, :calf, :chest,
            :hip, :thigh, :waist, :wrist,
            presence: true

  belongs_to :day

  delegate :registered_on, to: :day
end

app/models/priority.rb
class Priority < ApplicationRecord
  validates :name, presence: true

  belongs_to :user

  enum category: %i{ essential desirable very_desirable }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :email, presence: true

  with_options dependent: :destroy do
    has_many :days
    has_many :hungers
    has_many :priorities
    has_many :weights, through: :days
    has_many :perimeters, through: :days
    has_many :daily_activities, through: :days
  end
end

app/models/weight.rb
class Weight < ApplicationRecord
  validates :value, presence: true

  belongs_to :day

  delegate :registered_on, to: :day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  protect_from_forgery with: :exception

  before_action :require_login
end

app/controllers/concerns/new_create.rb
module NewCreate
  def new
    scope
    instance_variable_set(
      object_instance,
      object_key.to_s.camelize.constantize.new
    )
  end

  def create
    result = controller_name.camelize.constantize::CreationService.perform(
      object_params, scope
    )

    instance_variable_set(object_instance, result.public_send(object_key))

    if result.success?
      redirect_to after_creation_path, notice: t(".success")
    else
      render :new
    end
  end

  private

  def object_key
    controller_name.singularize.to_sym
  end

  def object_instance
    "@#{object_key}".to_sym
  end

  def object_params
    params.require(object_key).permit(permitted_attributes)
  end

  def after_creation_path
    root_path
  end

  def scope
    current_user
  end
end

app/controllers/concerns/resourceless.rb
module Resourceless
  include NewCreate

  def index
    instance_variable_set("@#{collection_key}".to_sym, collection.decorate)
  end

  def destroy
    instance_variable_set(object_instance, collection.find(params[:id])).destroy

    redirect_to after_destruction_path, notice: t('.success')
  end

  private

  def collection
    current_user.public_send(collection_key)
  end

  def collection_key
    controller_name.to_sym
  end

  def after_destruction_path
    after_creation_path
  end
end

app/controllers/daily_activities_controller.rb
class DailyActivitiesController < ApplicationController
  def index
    @daily_activities = current_user.daily_activities.decorate
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show; end
end

app/controllers/days/base_controller.rb
module Days
  class BaseController < ApplicationController

    private

    def day
      @day ||= current_user.days.find(params[:id])
    end
  end
end

app/controllers/days/perimeters_controller.rb
module Days
  class PerimetersController < BaseController
    include NewCreate

    private

    def permitted_attributes
      [
        :abdomen, :arm, :calf, :chest,
        :hip, :thigh, :waist, :wrist
      ]
    end

    def scope
      day
    end
  end
end

app/controllers/days/weights_controller.rb
module Days
  class WeightsController < BaseController
    include NewCreate

    private

    def permitted_attributes
      [:value]
    end

    def after_creation_path
      new_perimeter_path(@day)
    end

    def scope
      day
    end
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def new
    @day = Day.new
  end

  def create
    result = Days::CreationService.perform(day_params, current_user)

    @day = result.day

    if result.success?
      redirect_to new_daily_activity_path(@day), notice: t(".success")
    else
      render :new
    end
  end

  private

  def day_params
    params.require(:day).permit(:registered_on)
  end
end

app/controllers/hungers_controller.rb
class HungersController < ApplicationController
  include Resourceless

  private

  def permitted_attributes
    [
      :local, :question, :registered_at, :sensation, :classification
    ]
  end

  def after_creation_path
    hungers_path
  end
end

app/controllers/perimeters_controller.rb
class PerimetersController < ApplicationController
  def index
    @perimeters = current_user.perimeters.decorate
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  include Resourceless

  private

  def permitted_attributes
    [:name, :category]
  end

  def after_creation_path
    priorities_path
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def index
    @weights = current_user.weights.decorate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hungers/index.html.erb
<h1><%= t('.title') %></h1>

<%= link_to t(".new"), new_hunger_path %>

<h2><%= t(:hungers, count: @hungers.count) %></h2>

<% if @hungers.any? %>
  <table>
    <thead>
      <th>Data e Hora de Registro</th>
      <th>Local</th>
      <th>Sensações</th>
      <th>Perguntas-Chave</th>
      <th>Classificação</th>
    </thead>
    <tbody>
      <% @hungers.each do |hunger| %>
        <tr id="<%= dom_id(hunger) %>">
          <td><%= hunger.registered_at %></td>
          <td><%= hunger.local %></td>
          <td><%= hunger.sensation %></td>
          <td><%= hunger.question %></td>
          <td><%= hunger.classification %></td>
          <td><%= hunger.destroy_link %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/hungers/new.html.erb
<h1><%= t('.title') %></h1>

<%= simple_form_for @hunger do |f| %>
  <%= f.error_notification %>
  <%= f.input :registered_at, html5: true, required: true  %>
  <%= f.input :local, required: true %>
  <%= f.input :sensation, required: true %>
  <%= f.input :question, required: true %>
  <%= f.input :classification, required: true,
    collection: Hunger.classifications.map { |key,_|
      [I18n.t(key, scope: [:hunger, :enums, :classification]), key]
    }
  %>
  <%= f.button :submit, class: :button %>
  <%= link_to 'Cancelar', hungers_path %>
<% end %>

app/views/priorities/index.html.erb
<h1><%= t('.title') %></h1>

<%= link_to t(".new"), new_priority_path %>

<h2><%= t(:priorities, count: @priorities.count) %></h2>

<% if @priorities.any? %>
  <table>
    <thead>
      <th>Categoria</th>
      <th>Prioridade</th>
      <th></th>
    </thead>
    <tbody>
      <% @priorities.each do |priority| %>
        <tr>
          <td><%= priority.category %></td>
          <td><%= priority.name %></td>
          <td><%= priority.destroy_link %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/priorities/new.html.erb
<h1><%= t('.title') %></h1>

<%= simple_form_for @priority do |f| %>
  <%= f.error_notification %>
  <%= f.input :category, required: true,
    collection: Priority.categories.map { |key,_|
      [I18n.t(key, scope: [:priority, :enums, :category]), key]
    }
  %>
  <%= f.input :name, required: true %>
  <%= f.button :submit, class: :button %>
  <%= link_to 'Cancelar', priorities_path %>
<% end %>